spring:
  profiles:
    active: ${APP_PROFILE:dev}

server:
  port: 8080

management:
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
    info:
      enabled: true

logging:
  level:
    root: ${APP_LOGGING_LEVEL}